(cl:defpackage speech_pkg-srv
  (:use )
  (:export
   "CLASSIFICATION"
   "<CLASSIFICATION-REQUEST>"
   "CLASSIFICATION-REQUEST"
   "<CLASSIFICATION-RESPONSE>"
   "CLASSIFICATION-RESPONSE"
   "CLASSIFICATIONMSI"
   "<CLASSIFICATIONMSI-REQUEST>"
   "CLASSIFICATIONMSI-REQUEST"
   "<CLASSIFICATIONMSI-RESPONSE>"
   "CLASSIFICATIONMSI-RESPONSE"
   "MANAGER"
   "<MANAGER-REQUEST>"
   "MANAGER-REQUEST"
   "<MANAGER-RESPONSE>"
   "MANAGER-RESPONSE"
   "TALKER"
   "<TALKER-REQUEST>"
   "TALKER-REQUEST"
   "<TALKER-RESPONSE>"
   "TALKER-RESPONSE"
  ))

