(cl:defpackage iri_object_transportation_msgs-msg
  (:use )
  (:export
   "<EXPLICIT_INFORMATION>"
   "EXPLICIT_INFORMATION"
   "<LOCALFORCESCOEFFICIENTS>"
   "LOCALFORCESCOEFFICIENTS"
   "<LOCALFORCESSFM>"
   "LOCALFORCESSFM"
   "<NARROWPATHMARKERSARRAY>"
   "NARROWPATHMARKERSARRAY"
   "<TWISTSTAMPED>"
   "TWISTSTAMPED"
   "<TWISTSTAMPEDARRAY>"
   "TWISTSTAMPEDARRAY"
   "<WRENCHSTAMPEDARRAY>"
   "WRENCHSTAMPEDARRAY"
   "<WRENCHSTAMPEDWITHCOEFF>"
   "WRENCHSTAMPEDWITHCOEFF"
   "<WRENCHWITHCOEFFARRAY>"
   "WRENCHWITHCOEFFARRAY"
  ))

