// Generated by gencpp from file iri_object_transportation_msgs/localForcesCoefficients.msg
// DO NOT EDIT!


#ifndef IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_LOCALFORCESCOEFFICIENTS_H
#define IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_LOCALFORCESCOEFFICIENTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iri_object_transportation_msgs
{
template <class ContainerAllocator>
struct localForcesCoefficients_
{
  typedef localForcesCoefficients_<ContainerAllocator> Type;

  localForcesCoefficients_()
    : header()
    , goal_coefficient(0.0)
    , attractor_coefficient(0.0)
    , obstacles_coefficients()
    , total_coefficient(0.0)  {
    }
  localForcesCoefficients_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_coefficient(0.0)
    , attractor_coefficient(0.0)
    , obstacles_coefficients(_alloc)
    , total_coefficient(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _goal_coefficient_type;
  _goal_coefficient_type goal_coefficient;

   typedef float _attractor_coefficient_type;
  _attractor_coefficient_type attractor_coefficient;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _obstacles_coefficients_type;
  _obstacles_coefficients_type obstacles_coefficients;

   typedef float _total_coefficient_type;
  _total_coefficient_type total_coefficient;





  typedef boost::shared_ptr< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> const> ConstPtr;

}; // struct localForcesCoefficients_

typedef ::iri_object_transportation_msgs::localForcesCoefficients_<std::allocator<void> > localForcesCoefficients;

typedef boost::shared_ptr< ::iri_object_transportation_msgs::localForcesCoefficients > localForcesCoefficientsPtr;
typedef boost::shared_ptr< ::iri_object_transportation_msgs::localForcesCoefficients const> localForcesCoefficientsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_coefficient == rhs.goal_coefficient &&
    lhs.attractor_coefficient == rhs.attractor_coefficient &&
    lhs.obstacles_coefficients == rhs.obstacles_coefficients &&
    lhs.total_coefficient == rhs.total_coefficient;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_object_transportation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9b5321a9227a9197e9c265bb9376d55";
  }

  static const char* value(const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9b5321a9227a919ULL;
  static const uint64_t static_value2 = 0x7e9c265bb9376d55ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_object_transportation_msgs/localForcesCoefficients";
  }

  static const char* value(const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 goal_coefficient\n"
"float32 attractor_coefficient\n"
"float32[] obstacles_coefficients\n"
"float32 total_coefficient\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_coefficient);
      stream.next(m.attractor_coefficient);
      stream.next(m.obstacles_coefficients);
      stream.next(m.total_coefficient);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct localForcesCoefficients_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_object_transportation_msgs::localForcesCoefficients_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_coefficient: ";
    Printer<float>::stream(s, indent + "  ", v.goal_coefficient);
    s << indent << "attractor_coefficient: ";
    Printer<float>::stream(s, indent + "  ", v.attractor_coefficient);
    s << indent << "obstacles_coefficients[]" << std::endl;
    for (size_t i = 0; i < v.obstacles_coefficients.size(); ++i)
    {
      s << indent << "  obstacles_coefficients[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.obstacles_coefficients[i]);
    }
    s << indent << "total_coefficient: ";
    Printer<float>::stream(s, indent + "  ", v.total_coefficient);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_LOCALFORCESCOEFFICIENTS_H
