// Generated by gencpp from file iri_object_transportation_msgs/twistStampedArray.msg
// DO NOT EDIT!


#ifndef IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_TWISTSTAMPEDARRAY_H
#define IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_TWISTSTAMPEDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <iri_object_transportation_msgs/twistStamped.h>

namespace iri_object_transportation_msgs
{
template <class ContainerAllocator>
struct twistStampedArray_
{
  typedef twistStampedArray_<ContainerAllocator> Type;

  twistStampedArray_()
    : header()
    , twist_array()  {
    }
  twistStampedArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , twist_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::iri_object_transportation_msgs::twistStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::iri_object_transportation_msgs::twistStamped_<ContainerAllocator> >::other >  _twist_array_type;
  _twist_array_type twist_array;





  typedef boost::shared_ptr< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> const> ConstPtr;

}; // struct twistStampedArray_

typedef ::iri_object_transportation_msgs::twistStampedArray_<std::allocator<void> > twistStampedArray;

typedef boost::shared_ptr< ::iri_object_transportation_msgs::twistStampedArray > twistStampedArrayPtr;
typedef boost::shared_ptr< ::iri_object_transportation_msgs::twistStampedArray const> twistStampedArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.twist_array == rhs.twist_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_object_transportation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03e348c69a5cfa2196a94fd09cb86416";
  }

  static const char* value(const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03e348c69a5cfa21ULL;
  static const uint64_t static_value2 = 0x96a94fd09cb86416ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_object_transportation_msgs/twistStampedArray";
  }

  static const char* value(const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"iri_object_transportation_msgs/twistStamped[] twist_array\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: iri_object_transportation_msgs/twistStamped\n"
"std_msgs/Header header\n"
"geometry_msgs/Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.twist_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct twistStampedArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_object_transportation_msgs::twistStampedArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "twist_array[]" << std::endl;
    for (size_t i = 0; i < v.twist_array.size(); ++i)
    {
      s << indent << "  twist_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::iri_object_transportation_msgs::twistStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.twist_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_TWISTSTAMPEDARRAY_H
