COMMANDS = {
    "eng":{
        0: "Increase the height",
        1: "Decrease the height",
        2: "Increase the inclination",
        3: "Decrease the inclination",
        4: "Increase the illumination",
        5: "Decrease the illumination",
        6: "Increase the illumination 1",
        7: "Decrease the illumination 1",
        8: "Increase the illumination 2",
        9: "Decrease the illumination 2",
        10:"Bring me the gun screwdriver",
        11:"Take the gun screwdriver",
        12:"Bring me the elbow screwdriver",
        13:"Take the elbow screwdriver",
        14:"Bring me the windows control panel",
        15:"Take the windows control panel",
        16:"Bring me the window frame",
        17:"Take the window frame",
        18:"Bring me the speaker",
        19:"Take the speaker", 
        20:"Bring me the object holder",
        21:"Take the object holder",
        22:"Increase the speaker panel",
        23:"Take the speaker panel",
        24:"Open",
        25:"Close",
        26:"Release" 
    },
    "ita":{
        0: "Piu alto",
        1: "Piu basso",
        2: "Piu inclinato",
        3: "Meno inclinato",
        4: "Piu luce",
        5: "Meno luce",
        6: "Piu luce 1",
        7: "Meno luce 1",
        8: "Piu luce 2",
        9: "Meno luce 2",
        10:"Portami l avvitatore elettrico",
        11:"Prendi l avvitatore elettrico",
        12:"Portami l avvitatore a gomito",
        13:"Prendi l avvitatore a gomito",
        14:"Portami la mostrina comandi",
        15:"Prendi la mostrina comandi",
        16:"Portami il voletto",
        17:"Prendi il voletto",
        18:"Portami l altoparlante",
        19:"Prendi l altoparlante", 
        20:"Portami il porta oggetti",
        21:"Prendi il porta oggetti",
        22:"Portami la mostrina altoparlante",
        23:"Prendi la mostrina altoparlante",
        24:"Apri",
        25:"Chiudi",
        26:"Rilascia" 
    }
}