INTENT_REPETITIONS: int = 3
INTENTS_DICT: dict = {
    0   :   {"eng": {0:"start (not urgent)"},
             "ita": {0:"inizia (non urgente)"},
             "esp": {0:"comienza (no urgente)"}},
    1   :   {"eng": {0:"start (urgent)",
                     1:"start immediately (urgent)",
                     2:"start now (urgent)",
                     3:"start quickly (urgent)"},
             "ita": {0:"inizia (urgente)",
                     1:"inizia immediatamente (urgente)",
                     2:"inizia ora (urgente)"},
             "esp": {0:"comienza (urgente)",
                     1:"comienza inmediatamente (urgente)",
                     2:"inizia ahora (urgente)"}},
    2   :   {"eng": {0:"go ahead (not urgent)",
                     1:"ahead (not urgent)"},
             "ita": {0:"vai avanti (non urgente)",
                     1:"avanti (non urgente)"},
             "esp": {0:"adelante (no urgente)"}},
    3   :   {"eng": {0:"go ahead (urgent)",
                     1:"ahead (urgent)",
                     2:"go ahead immediately (urgent)",
                     3:"ahead immediately (urgent)",
                     4:"go ahead now (urgent)",
                     5:"ahead now (urgent)",
                     6:"go ahead quickly (urgent)",
                     7:"ahead quickly (urgent)"},
             "ita": {0:"vai avanti (urgente)",
                     1:"avanti (urgente)",
                     2:"vai avanti immediatamente (urgente)",
                     3:"avanti immediatamente (urgente)",
                     4:"vai avanti ora (urgente)",
                     5:"avanti ora (urgente)"},
             "esp": {0:"adelante (urgente)",
                     1:"adelante inmediatamente (urgente)",
                     2:"adelante ahora (urgente)"}},
    4   :   {"eng": {0:"go back (not urgent)",
                     1:"back (not urgent)"},
             "ita": {0:"vai indietro (non urgente)",
                     1:"indietro (non urgente)"},
             "esp": {0:"regresa (no urgente)",
                     1:"ve para atrás (no urgente)",
                     2:"atrás (no urgente)"}},
    5   :   {"eng": {0:"go back (urgent)",
                     1:"back (urgent)",
                     2:"go back immediately (urgent)",
                     3:"back immediately (urgent)",
                     4:"go back now (urgent)",
                     5:"back now (urgent)",
                     6:"go back quickly (urgent)",
                     7:"back quickly (urgent)"},
             "ita": {0:"vai indietro (urgente)",
                     1:"indietro (urgente)",
                     2:"vai indietro immediatamente (urgente)",
                     3:"indietro immediatamente (urgente)",
                     4:"vai indietro ora (urgente)",
                     5:"indietro ora (urgente)"},
             "esp": {0:"regresa (urgente)",
                     1:"ve para atrás (urgente)",
                     2:"atrás (urgente)",
                     3:"regresa inmediatamente (urgente)",
                     4:"ve para atrás inmediatamente (urgente)",
                     5:"atrás inmediatamente (urgente)",
                     6:"regresa ahora (urgente)",
                     7:"ve para atrás ahora (urgente)",
                     8:"atrás ahora (urgente)"}}
}