INTENT_REPETITIONS:int = 3
INTENTS_DICT:dict = {
    0   :   {"eng": {0:"start (not urgent)"},
             "ita": {0:"inizia (non urgente)"},
             "esp": {0:"comienza (no urgente)"}},
    1   :   {"eng": {0:"start",
                     1:"start immediately",
                     2:"start now",
                     3:"start quickly"},
             "ita": {0:"inizia",
                     1:"inizia immediatamente",
                     2:"inizia ora"},
             "esp": {0:"comienza",
                     1:"comienza inmediatamente",
                     2:"inizia ahora"}},
    2   :   {"eng": {0:"go ahead (not urgent)",
                     1:"ahead (not urgent)"},
             "ita": {0:"vai avanti (non urgente)",
                     1:"avanti (non urgente)"},
             "esp": {0:"adelante (no urgente)"}},
    3   :   {"eng": {0:"go ahead",
                     1:"ahead",
                     2:"go ahead immediately",
                     3:"ahead immediately",
                     4:"go ahead now",
                     5:"ahead now",
                     6:"go ahead quickly",
                     7:"ahead quickly"},
             "ita": {0:"vai avanti",
                     1:"avanti",
                     2:"vai avanti immediatamente",
                     3:"avanti immediatamente",
                     4:"vai avanti ora",
                     5:"avanti ora"},
             "esp": {0:"adelante",
                     1:"adelante inmediatamente",
                     2:"adelante ahora"}},
    4   :   {"eng": {0:"go back (not urgent)",
                     1:"back (not urgent)"},
             "ita": {0:"vai indietro (non urgente)",
                     1:"indietro (non urgente)"},
             "esp": {0:"regresa (no urgente)",
                     1:"ve para atrás (no urgente)",
                     2:"atrás (no urgente)"}},
    5   :   {"eng": {0:"go back",
                     1:"back",
                     2:"go back immediately",
                     3:"back immediately",
                     4:"go back now",
                     5:"back now",
                     6:"go back quickly",
                     7:"back quickly"},
             "ita": {0:"vai indietro",
                     1:"indietro",
                     2:"vai indietro immediatamente",
                     3:"indietro immediatamente",
                     4:"vai indietro ora",
                     5:"indietro ora"},
             "esp": {0:"regresa",
                     1:"ve para atrás",
                     2:"atrás",
                     3:"regresa inmediatamente",
                     4:"ve para atrás inmediatamente",
                     5:"atrás inmediatamente",
                     6:"regresa ahora",
                     7:"ve para atrás ahora",
                     8:"atrás ahora"}},
    6   :   {"eng": {0:"go left (not urgent)",
                     1:"left (not urgent)"},
             "ita": {0:"vai a sinistra (non urgente)",
                     1:"sinistra (non urgente)"},
             "esp": {0:"ve a la izquierda (no urgente)",
                     1:"izquierda (no urgente)"}},
    7   :   {"eng": {0:"go left",
                     1:"left",
                     2:"go left immediately",
                     3:"left immediately",
                     4:"go left now",
                     5:"left now",
                     6:"go left quickly",
                     7:"left quickly"},
             "ita": {0:"vai a sinistra",
                     1:"sinistra",
                     2:"vai a sinistra immediatamente",
                     3:"sinistra immediatamente",
                     4:"vai a sinistra ora",
                     5:"sinistra ora"},
             "esp": {0:"ve a la izquierda",
                     1:"izquierda",
                     2:"ve a la izquierda inmediatamente",
                     3:"izquierda inmediatamente",
                     4:"ve a la izquierda ahora",
                     5:"izquierda ahora"}},
    8   :   {"eng": {0:"go right (not urgent)",
                     1:"right (not urgent)"},
             "ita": {0:"vai a destra (non urgente)",
                     1:"destra (non urgente)"},
             "esp": {0:"ve a la derecha (no urgente)",
                     1:"derecha (no urgente)"}},
    9   :   {"eng": {0:"go right",
                     1:"right",
                     2:"go right immediately",
                     3:"right immediately",
                     4:"go right now",
                     5:"right now",
                     6:"go right quickly",
                     7:"right quickly"},
             "ita": {0:"vai a destra",
                     1:"destra",
                     2:"vai a destra immediatamente",
                     3:"destra immediatamente",
                     4:"vai a destra ora",
                     5:"destra ora"},
             "esp": {0:"ve a la derecha",
                     1:"derecha",
                     2:"ve a la derecha inmediatamente",
                     3:"derecha inmediatamente",
                     4:"ve a la derecha ahora",
                     5:"derecha ahora"}},
    10  :   {"eng": {0:"stop (not urgent)"},
             "ita": {0:"stop (non urgente)",
                     1:"fermati (non urgente)"},
             "esp": {0:"stop (no urgente)",
                     1:"detente (no urgente)"}},
    11  :   {"eng": {0:"stop",
                     1:"stop immediately",
                     2:"stop now",
                     3:"stop quickly"},
             "ita": {0:"stop",
                     1:"fermati",
                     2:"stop immediatamente",
                     3:"fermati immediatamente",
                     4:"stop ora",
                     5:"fermati ora"},
             "esp": {0:"stop",
                     1:"detente",
                     2:"stop inmediatamente",
                     3:"detente inmediatamente",
                     4:"stop ahora",
                     5:"detente ahora"}},
    12  :   {"eng": {0:"come (not urgent)",
                     1:"come here (not urgent)"},
             "ita": {0:"vieni (non urgente)",
                     1:"vieni qui (non urgente)"},
             "esp": {0:"acercate (no urgente)",
                     1:"ven aquì (no urgente)"}},
    13  :   {"eng": {0:"come",
                     1:"come here",
                     2:"come immediately",
                     3:"come here immediately",
                     4:"come now",
                     5:"come here now",
                     6:"come quickly",
                     7:"come here quickly"},
             "ita": {0:"vieni",
                     1:"vieni qui",
                     2:"vieni immediatamente",
                     3:"vieni qui immediatamente",
                     4:"vieni qui ora",
                     5:"vieni ora"},
             "esp": {0:"acercate",
                     1:"ven aquì",
                     2:"acercate inmediatamente",
                     3:"ven aquì inmediatamente",
                     4:"acercate ahora",
                     5:"ven aquì ahora"}},
    14  :   {"eng": {0:"release (not urgent)",
                     1:"drop (not urgent)"},
             "ita": {0:"rilascia (non urgente)",
                     1:"lascia (non urgente)"},
             "esp": {0:"suelta (no urgente)",
                     1:"deja (no urgente)"}},
    15  :   {"eng": {0:"release",
                     1:"drop",
                     2:"release immediately",
                     3:"drop immediately",
                     4:"release now",
                     5:"drop now",
                     6:"release quickly",
                     7:"drop quickly"},
             "ita": {0:"rilascia",
                     1:"lascia",
                     2:"rilascia immediatamente",
                     3:"lascia immediatamente",
                     4:"rilascia ora",
                     5:"lascia ora"},
             "esp": {0:"suelta",
                     1:"deja",
                     2:"suelta inmediatamente",
                     3:"deja inmediatamente",
                     4:"suelta ahora",
                     5:"deja ahora"}},
    16  :   {"eng": {0:"fast (not urgent)",
                     1:"faster (not urgent)",
                     2:"quickly"},
             "ita": {0:"veloce (non urgente)",
                     1:"più veloce (non urgente)",
                     2:"velocemente (no urgente)"},
             "esp": {0:"rapido",
                     1:"más rapido",
                     2:"rapidamente"}},
    17  :   {"eng": {0:"slow (not urgent)",
                     1:"slower (not urgent)",
                     2:"slowly (not urgent)"},
             "ita": {0:"lento (non urgente)",
                     1:"più lento (non urgente)",
                     2:"lentamente (non urgente)"},
             "esp": {0:"lento (no urgente)",
                     1:"más lento (no urgente)",
                     2:"lentamente (no urgente)"}},
    18  :   {"eng": {0:"yes (not urgent)",
                     1:"okay (not urgent)"},
             "ita": {0:"si (non urgente)",
                     1:"va bene (non urgente)"},
             "esp": {0:"si (no urgente)",
                     1:"vale (no urgente)"}},
    19  :   {"eng": {0:"no (not urgent)"},
             "ita": {0:"no (non urgente)"},
             "esp": {0:"no (no urgente)"}},
    20  :   {"eng": {0:"maybe (not urgent)",
                     1:"i don't know (not urgent)"},
             "ita": {0:"forse (non urgente)",
                     1:"non lo so (non urgente)"},
             "esp": {0:"tal vez (no urgente)",
                     1:"no sé (no urgente)"}},
    21  :   {"eng": {0:"help me (not urgent)"},
             "ita": {0:"aiutami (non urgente)"},
             "esp": {0:"ayùdame (no urgente)"}},
    22  :   {"eng": {0:"help me",
                     1:"help me immediately",
                     2:"help me now",
                     3:"help me quickly"},
             "ita": {0:"aiutami",
                     1:"aiutami immediatamente",
                     2:"aiutami ora"},
             "esp": {0:"ayùdame",
                     1:"ayùdame inmediatamente",
                     2:"ayùdame ahora"}}
}
REDUCED_INTENTS_DICT_MSIEXP0:dict = {
    0   :   {"eng": {0:"go left",
                     1:"left",
                     2:"go left immediately",
                     3:"left immediately",
                     4:"go left now",
                     5:"left now",
                     6:"go left quickly",
                     7:"left quickly"},
             "ita": {0:"vai a sinistra",
                     1:"sinistra",
                     2:"vai a sinistra immediatamente",
                     3:"sinistra immediatamente",
                     4:"vai a sinistra ora",
                     5:"sinistra ora"},
             "esp": {0:"ve a la izquierda",
                     1:"izquierda",
                     2:"ve a la izquierda inmediatamente",
                     3:"izquierda inmediatamente",
                     4:"ve a la izquierda ahora",
                     5:"izquierda ahora"}},
    1   :   {"eng": {0:"go ahead",
                     1:"ahead",
                     2:"go ahead immediately",
                     3:"ahead immediately",
                     4:"go ahead now",
                     5:"ahead now",
                     6:"go ahead quickly",
                     7:"ahead quickly"},
             "ita": {0:"vai avanti",
                     1:"avanti",
                     2:"vai avanti immediatamente",
                     3:"avanti immediatamente",
                     4:"vai avanti ora",
                     5:"avanti ora"},
             "esp": {0:"adelante",
                     1:"adelante inmediatamente",
                     2:"adelante ahora"}},
    2   :   {"eng": {0:"go right",
                     1:"right",
                     2:"go right immediately",
                     3:"right immediately",
                     4:"go right now",
                     5:"right now",
                     6:"go right quickly",
                     7:"right quickly"},
             "ita": {0:"vai a destra",
                     1:"destra",
                     2:"vai a destra immediatamente",
                     3:"destra immediatamente",
                     4:"vai a destra ora",
                     5:"destra ora"},
             "esp": {0:"ve a la derecha",
                     1:"derecha",
                     2:"ve a la derecha inmediatamente",
                     3:"derecha inmediatamente",
                     4:"ve a la derecha ahora",
                     5:"derecha ahora"}},
    3  :   {"eng": {0:"stop",
                     1:"stop immediately",
                     2:"stop now",
                     3:"stop quickly"},
             "ita": {0:"stop",
                     1:"fermati",
                     2:"stop immediatamente",
                     3:"fermati immediatamente",
                     4:"stop ora",
                     5:"fermati ora"},
             "esp": {0:"stop",
                     1:"detente",
                     2:"stop inmediatamente",
                     3:"detente inmediatamente",
                     4:"stop ahora",
                     5:"detente ahora"}},
}
CONVERSION_DICT_MSIEXP0:dict = {
    6:0,
    7:0,
    2:1,
    3:1,
    8:2,
    9:2,
    10:3,
    11:3
}

REDUCED_INTENTS_DICT_MSIexp1:dict = {
    0:  {
        "explicit": {
            "eng":{0:{"id":0, "text":"go ahead"},
                   1:{"id":1, "text":"ahead"}},
            "esp":{0:{"id":0, "text":"adelante"}},
            "ita":{0:{"id":0, "text":"vai avanti"},
                   1:{"id":1, "text":"avanti"}}
            },
        "implicit": {
            "eng":{"id":0, "text":"not urgent"},
            "esp":{"id":0, "text":"non urgente"},
            "ita":{"id":0, "text":"no urgente"}
            }
        },
    1:  {
        "explicit": {
            "eng":{0:{"id":0, "text":"go ahead"},
                   1:{"id":1, "text":"ahead"},
                   2:{"id":2, "text":"go ahead immediately"},
                   3:{"id":3, "text":"ahead immediately"},
                   4:{"id":4, "text":"go ahead now"},
                   5:{"id":5, "text":"ahead now"},
                   6:{"id":6, "text":"go ahead quickly"},
                   7:{"id":7, "text":"ahead quickly"}},
            "esp":{0:{"id":0, "text":"adelante"},
                   1:{"id":1, "text":"adelante inmediatamente"},
                   2:{"id":2, "text":"adelante ahora"}},
            "ita":{0:{"id":0, "text":"vai avanti"},
                   1:{"id":1, "text":"avanti"},
                   2:{"id":2, "text":"vai avanti immediatamente"},
                   3:{"id":3, "text":"avanti immediatamente"},
                   4:{"id":4, "text":"vai avanti ora"},
                   5:{"id":5, "text":"avanti ora"}}
            },
        "implicit": {
            "eng":{"id":1, "text":"urgent"},
            "esp":{"id":1, "text":"urgente"},
            "ita":{"id":1, "text":"urgente"}
            }
        },
    2:  {
        "explicit": {
            "eng":{0:{"id":8, "text":"go back"},
                   1:{"id":9, "text":"back"}},
            "esp":{0:{"id":3, "text":"regresa"},
                   1:{"id":4, "text":"ve para atrás"},
                   2:{"id":5, "text":"atrás"}},
            "ita":{0:{"id":6, "text":"vai indietro"},
                   1:{"id":7, "text":"indietro"}}
            },
        "implicit":{
            "eng":{"id":0, "text":"not urgent"},
            "esp":{"id":0, "text":"non urgente"},
            "ita":{"id":0, "text":"no urgente"}
            }
        },
    3:  {
        "explicit":{
            "eng":{0:{"id":8, "text":"go back"},
                   1:{"id":9, "text":"back"},
                   2:{"id":10, "text":"go back immediately"},
                   3:{"id":11, "text":"back immediately"},
                   4:{"id":12, "text":"go back now"},
                   5:{"id":13, "text":"back now"},
                   6:{"id":14, "text":"go back quickly"},
                   7:{"id":15, "text":"back quickly"}},
            "esp":{0:{"id":3, "text":"regresa"},
                   1:{"id":4, "text":"ve para atrás"},
                   2:{"id":5, "text":"atrás"},
                   3:{"id":6, "text":"regresa inmediatamente"},
                   4:{"id":7, "text":"ve para atrás inmediatamente"},
                   5:{"id":8, "text":"atrás inmediatamente"},
                   6:{"id":9, "text":"regresa ahora"},
                   7:{"id":10, "text":"ve para atrás ahora"},
                   8:{"id":11, "text":"atrás ahora"}},
            "ita":{0:{"id":6, "text":"vai indietro"},
                   1:{"id":7, "text":"indietro"},
                   2:{"id":8, "text":"vai indietro immediatamente"},
                   3:{"id":9, "text":"indietro immediatamente"},
                   4:{"id":10, "text":"vai indietro ora"},
                   5:{"id":11, "text":"indietro ora"}}
            },
        "implicit":{
            "eng":{"id":1, "text":"urgent"},
            "esp":{"id":1, "text":"urgente"},
            "ita":{"id":1, "text":"urgente"}
            }
        },
    4:  {
        "explicit":{
            "eng":{0:{"id":16, "text":"go left"},
                   1:{"id":17, "text":"left"}},
            "esp":{0:{"id":12, "text":"ve a la izquierda"},
                   1:{"id":13, "text":"izquierda"}},
            "ita":{0:{"id":12, "text":"vai a sinistra"},
                   1:{"id":13, "text":"sinistra"}}
            },
        "implicit":{
            "eng":{"id":0, "text":"not urgent"},
            "esp":{"id":0, "text":"non urgente"},
            "ita":{"id":0, "text":"no urgente"}
            }
        },
    5:  {
        "explicit":{
            "eng":{0:{"id":16, "text":"go left"},
                   1:{"id":17, "text":"left"},
                   2:{"id":18, "text":"go left immediately"},
                   3:{"id":19, "text":"left immediately"},
                   4:{"id":20, "text":"go left now"},
                   5:{"id":21, "text":"left now"},
                   6:{"id":22, "text":"go left quickly"},
                   7:{"id":23, "text":"left quickly"}},
            "esp":{0:{"id":12, "text":"ve a la izquierda"},
                   1:{"id":13, "text":"izquierda"},
                   2:{"id":14, "text":"ve a la izquierda inmediatamente"},
                   3:{"id":15, "text":"izquierda inmediatamente"},
                   4:{"id":16, "text":"ve a la izquierda ahora"},
                   5:{"id":17, "text":"izquierda ahora"}},
            "ita":{0:{"id":12, "text":"vai a sinistra"},
                   1:{"id":13, "text":"sinistra"},
                   2:{"id":14, "text":"vai a sinistra immediatamente"},
                   3:{"id":15, "text":"sinistra immediatamente"},
                   4:{"id":16, "text":"vai a sinistra ora"},
                   5:{"id":17, "text":"sinistra ora"}}
            },
        "implicit":{
            "eng":{"id":1, "text":"urgent"},
            "esp":{"id":1, "text":"urgente"},
            "ita":{"id":1, "text":"urgente"}
            }
        },
    6:  {
        "explicit":{
            "eng":{0:{"id":24, "text":"go right"},
                   1:{"id":25, "text":"right"}},
            "esp":{0:{"id":18, "text":"ve a la derecha"},
                   1:{"id":19, "text":"derecha"}},
            "ita":{0:{"id":18, "text":"vai a destra"},
                   1:{"id":19, "text":"destra"}}
            },
        "implicit":{
            "eng":{"id":0, "text":"not urgent"},
            "esp":{"id":0, "text":"non urgente"},
            "ita":{"id":0, "text":"no urgente"}
            }
        },
    7:  {
        "explicit":{
            "eng":{0:{"id":24, "text":"go right"},
                   1:{"id":25, "text":"right"},
                   2:{"id":26, "text":"go right immediately"},
                   3:{"id":27, "text":"right immediately"},
                   4:{"id":28, "text":"go right now"},
                   5:{"id":29, "text":"right now"},
                   6:{"id":30, "text":"go right quickly"},
                   7:{"id":31, "text":"right quickly"}},
            "esp":{0:{"id":18, "text":"ve a la derecha"},
                   1:{"id":19, "text":"derecha"},
                   2:{"id":20, "text":"ve a la derecha inmediatamente"},
                   3:{"id":21, "text":"derecha inmediatamente"},
                   4:{"id":22, "text":"ve a la derecha ahora"},
                   5:{"id":23, "text":"derecha ahora"}},
            "ita":{0:{"id":18, "text":"vai a destra"},
                   1:{"id":19, "text":"destra"},
                   2:{"id":20, "text":"vai a destra immediatamente"},
                   3:{"id":21, "text":"destra immediatamente"},
                   4:{"id":22, "text":"vai a destra ora"},
                   5:{"id":23, "text":"destra ora"}}
            },
        "implicit":{
            "eng":{"id":1, "text":"urgent"},
            "esp":{"id":1, "text":"urgente"},
            "ita":{"id":1, "text":"urgente"}
            }
        },
    8: {
        "explicit":{
            "eng":{0:{"id":32, "text":"stop"}},
            "esp":{0:{"id":24, "text":"stop"},
                   1:{"id":25, "text":"detente"}},
            "ita":{0:{"id":24, "text":"stop"},
                   1:{"id":25, "text":"fermati"}}
            },
        "implicit":{
            "eng":{"id":0, "text":"not urgent"},
            "esp":{"id":0, "text":"non urgente"},
            "ita":{"id":0, "text":"no urgente"}
            }
        },
    9: {
        "explicit":{
            "eng":{0:{"id":32, "text":"stop"},
                   1:{"id":33, "text":"stop immediately"},
                   2:{"id":34, "text":"stop now"},
                   3:{"id":35, "text":"stop quickly"}},
            "esp":{0:{"id":24, "text":"stop"},
                   1:{"id":25, "text":"detente"},
                   2:{"id":26, "text":"stop inmediatamente"},
                   3:{"id":27, "text":"detente inmediatamente"},
                   4:{"id":28, "text":"stop ahora"},
                   5:{"id":29, "text":"detente ahora"}},
            "ita":{0:{"id":24, "text":"stop"},
                   1:{"id":25, "text":"fermati"},
                   2:{"id":26, "text":"stop immediatamente"},
                   3:{"id":27, "text":"fermati immediatamente"},
                   4:{"id":28, "text":"stop ora"},
                   5:{"id":29, "text":"fermati ora"}}
            },
        "implicit":{
            "eng":{"id":1, "text":"urgent"},
            "esp":{"id":1, "text":"urgente"},
            "ita":{"id":1, "text":"urgente"}
            }
        },
    10: {
        "explicit":{
            "eng":{0:{"id":36, "text":"come"},
                   1:{"id":37, "text":"come here"}},
            "esp":{0:{"id":30, "text":"ven aquì"},
                   1:{"id":31, "text":"acercate"}},
            "ita":{0:{"id":30, "text":"vieni"},
                   1:{"id":31, "text":"vieni qui"}}
            },
        "implicit":{
            "eng":{"id":0, "text":"not urgent"},
            "esp":{"id":0, "text":"non urgente"},
            "ita":{"id":0, "text":"no urgente"}
            }
        },
    11: {
        "explicit":{
            "eng":{0:{"id":36, "text":"come"},
                   1:{"id":37, "text":"come here"},
                   2:{"id":38, "text":"come immediately"},
                   3:{"id":39, "text":"come here immediately"},
                   4:{"id":40, "text":"come now"},
                   5:{"id":41, "text":"come here now"},
                   6:{"id":42, "text":"come quickly"},
                   7:{"id":43, "text":"come here quickly"}},
            "esp":{0:{"id":30, "text":"ven aqui"},
                   1:{"id":31, "text":"acercate"},
                   2:{"id":32, "text":"ven aquì inmediatamente"},
                   3:{"id":33, "text":"acercate inmediatamente"},
                   4:{"id":34, "text":"ven aquì ahora"},
                   5:{"id":35, "text":"acercate ahora"}},
            "ita":{0:{"id":30, "text":"vieni"},
                   1:{"id":31, "text":"vieni qui"},
                   2:{"id":32, "text":"vieni immediatamente"},
                   3:{"id":33, "text":"vieni qui immediatamente"},
                   4:{"id":34, "text":"vieni qui ora"},
                   5:{"id":35, "text":"vieni ora"}}
            },
        "implicit":{
            "eng":{"id":1, "text":"urgent"},
            "esp":{"id":1, "text":"urgente"},
            "ita":{"id":1, "text":"urgente"}
            }
        },
    12: {
        "explicit":{
            "eng":{0:{"id":44, "text":"chatter"}},
            "esp":{0:{"id":36, "text":"charla"}},
            "ita":{0:{"id":36, "text":"chiacchiere"}}
            },
        "implicit":{
            "eng":{"id":0, "text":"not urgent"},
            "esp":{"id":0, "text":"no urgente"},
            "ita":{"id":0, "text":"non urgente"}
            }
    }
}
CONVERSION_DICT_MSI:dict = {
    2:0,
    3:1,
    4:2,
    5:3,
    6:4,
    7:5,
    8:6,
    9:7,
    10:8,
    11:9,
    12:10,
    13:11
}