INTENT_REPETITIONS: int = 3
INTENTS_DICT: dict = {
    0   :   {"eng": {0:"start (not urgent)"},
             "ita": {0:"inizia (non urgente)"},
             "esp": {0:"comienza (no urgente)"}},
    1   :   {"eng": {0:"start (urgent)",
                     1:"start immediately (urgent)",
                     2:"start now (urgent)",
                     3:"start quickly (urgent)"},
             "ita": {0:"inizia (urgente)",
                     1:"inizia immediatamente (urgente)",
                     2:"inizia ora (urgente)"},
             "esp": {0:"comienza (urgente)",
                     1:"comienza inmediatamente (urgente)",
                     2:"inizia ahora (urgente)"}},
    2   :   {"eng": {0:"go ahead (not urgent)",
                     1:"ahead (not urgent)"},
             "ita": {0:"vai avanti (non urgente)",
                     1:"avanti (non urgente)"},
             "esp": {0:"adelante (no urgente)"}},
    3   :   {"eng": {0:"go ahead (urgent)",
                     1:"ahead (urgent)",
                     2:"go ahead immediately (urgent)",
                     3:"ahead immediately (urgent)",
                     4:"go ahead now (urgent)",
                     5:"ahead now (urgent)",
                     6:"go ahead quickly (urgent)",
                     7:"ahead quickly (urgent)"},
             "ita": {0:"vai avanti (urgente)",
                     1:"avanti (urgente)",
                     2:"vai avanti immediatamente (urgente)",
                     3:"avanti immediatamente (urgente)",
                     4:"vai avanti ora (urgente)",
                     5:"avanti ora (urgente)"},
             "esp": {0:"adelante (urgente)",
                     1:"adelante inmediatamente (urgente)",
                     2:"adelante ahora (urgente)"}},
    4   :   {"eng": {0:"go back (not urgent)",
                     1:"back (not urgent)"},
             "ita": {0:"vai indietro (non urgente)",
                     1:"indietro (non urgente)"},
             "esp": {0:"regresa (no urgente)",
                     1:"ve para atrás (no urgente)",
                     2:"atrás (no urgente)"}},
    5   :   {"eng": {0:"go back (urgent)",
                     1:"back (urgent)",
                     2:"go back immediately (urgent)",
                     3:"back immediately (urgent)",
                     4:"go back now (urgent)",
                     5:"back now (urgent)",
                     6:"go back quickly (urgent)",
                     7:"back quickly (urgent)"},
             "ita": {0:"vai indietro (urgente)",
                     1:"indietro (urgente)",
                     2:"vai indietro immediatamente (urgente)",
                     3:"indietro immediatamente (urgente)",
                     4:"vai indietro ora (urgente)",
                     5:"indietro ora (urgente)"},
             "esp": {0:"regresa (urgente)",
                     1:"ve para atrás (urgente)",
                     2:"atrás (urgente)",
                     3:"regresa inmediatamente (urgente)",
                     4:"ve para atrás inmediatamente (urgente)",
                     5:"atrás inmediatamente (urgente)",
                     6:"regresa ahora (urgente)",
                     7:"ve para atrás ahora (urgente)",
                     8:"atrás ahora (urgente)"}},
    6   :   {"eng": {0:"go left (not urgent)",
                     1:"left (not urgent)"},
             "ita": {0:"vai a sinistra (non urgente)",
                     1:"sinistra (non urgente)"},
             "esp": {0:"ve a la izquierda (no urgente)",
                     1:"izquierda (no urgente)"}},
    7   :   {"eng": {0:"go left (urgent)",
                     1:"left (urgent)",
                     2:"go left immediately (urgent)",
                     3:"left immediately (urgent)",
                     4:"go left now (urgent)",
                     5:"left now (urgent)",
                     6:"go left quickly (urgent)",
                     7:"left quickly (urgent)"},
             "ita": {0:"vai a sinistra (urgente)",
                     1:"sinistra (urgente)",
                     2:"vai a sinistra immediatamente (urgente)",
                     3:"sinistra immediatamente (urgente)",
                     4:"vai a sinistra ora (urgente)",
                     5:"sinistra ora (urgente)"},
             "esp": {0:"ve a la izquierda (urgente)",
                     1:"izquierda (urgente)",
                     2:"ve a la izquierda inmediatamente (urgente)",
                     3:"izquierda inmediatamente (urgente)",
                     4:"ve a la izquierda ahora (urgente)",
                     5:"izquierda ahora (urgente)"}},
    8   :   {"eng": {0:"go right (not urgent)",
                     1:"right (not urgent)"},
             "ita": {0:"vai a destra (non urgente)",
                     1:"destra (non urgente)"},
             "esp": {0:"ve a la derecha (no urgente)",
                     1:"derecha (no urgente)"}},
    9   :   {"eng": {0:"go right (urgent)",
                     1:"right (urgent)",
                     2:"go right immediately (urgent)",
                     3:"right immediately (urgent)",
                     4:"go right now (urgent)",
                     5:"right now (urgent)",
                     6:"go right quickly (urgent)",
                     7:"right quickly (urgent)"},
             "ita": {0:"vai a destra (urgente)",
                     1:"destra (urgente)",
                     2:"vai a destra immediatamente (urgente)",
                     3:"destra immediatamente (urgente)",
                     4:"vai a destra ora (urgente)",
                     5:"destra ora (urgente)"},
             "esp": {0:"ve a la derecha (urgente)",
                     1:"derecha (urgente)",
                     2:"ve a la derecha inmediatamente (urgente)",
                     3:"derecha inmediatamente (urgente)",
                     4:"ve a la derecha ahora (urgente)",
                     5:"derecha ahora (urgente)"}},
    10  :   {"eng": {0:"stop (not urgent)"},
             "ita": {0:"stop (non urgente)",
                     1:"fermati (non urgente)"},
             "esp": {0:"stop (no urgente)",
                     1:"detente (no urgente)"}},
    11  :   {"eng": {0:"stop (urgent)",
                     1:"stop immediately (urgent)",
                     2:"stop now (urgent)",
                     3:"stop quickly (urgent)"},
             "ita": {0:"stop (urgente)",
                     1:"fermati (urgente)",
                     2:"stop immediatamente (urgente)",
                     3:"fermati immediatamente (urgente)",
                     4:"stop ora (urgente)",
                     5:"fermati ora (urgente)"},
             "esp": {0:"stop (urgente)",
                     1:"detente (urgente)",
                     2:"stop inmediatamente (urgente)",
                     3:"detente inmediatamente (urgente)",
                     4:"stop ahora (urgente)",
                     5:"detente ahora (urgente)"}},
    12  :   {"eng": {0:"come (not urgent)",
                     1:"come here (not urgent)"},
             "ita": {0:"vieni (non urgente)",
                     1:"vieni qui (non urgente)"},
             "esp": {0:"ven aquì (no urgente)",
                     1:"acercate (no urgente)"}},
    13  :   {"eng": {0:"come (urgent)",
                     1:"come here (urgent)",
                     2:"come immediately (urgent)",
                     3:"come here immediately (urgent)",
                     4:"come now (urgent)",
                     5:"come here now (urgent)",
                     6:"come quickly (urgent)",
                     7:"come here quickly (urgent)"},
             "ita": {0:"vieni (urgente)",
                     1:"vieni qui (urgente)",
                     2:"vieni immediatamente (urgente)",
                     3:"vieni qui immediatamente (urgente)",
                     4:"vieni qui ora (urgente)",
                     5:"vieni ora (urgente)"},
             "esp": {0:"ven aqui (urgente)",
                     1:"acercate (urgente)",
                     2:"ven aquì inmediatamente (urgente)",
                     3:"acercate inmediatamente (urgente)",
                     4:"ven aquì ahora (urgente)",
                     5:"acercate ahora (urgente)"}},
    14  :   {"eng": {0:"release (not urgent)",
                     1:"drop (not urgent)"},
             "ita": {0:"rilascia (non urgente)",
                     1:"lascia (non urgente)"},
             "esp": {0:"suelta (no urgente)",
                     1:"deja (no urgente)"}},
    15  :   {"eng": {0:"release (urgent)",
                     1:"drop (urgent)",
                     2:"release immediately (urgent)",
                     3:"drop immediately (urgent)",
                     4:"release now (urgent)",
                     5:"drop now (urgent)",
                     6:"release quickly (urgent)",
                     7:"drop quickly (urgent)"},
             "ita": {0:"rilascia (urgente)",
                     1:"lascia (urgente)",
                     2:"rilascia immediatamente (urgente)",
                     3:"lascia immediatamente (urgente)",
                     4:"rilascia ora (urgente)",
                     5:"lascia ora (urgente)"},
             "esp": {0:"suelta (urgente)",
                     1:"deja atrás (urgente)",
                     2:"suelta inmediatamente (urgente)",
                     3:"deja inmediatamente (urgente)",
                     4:"suelta ahora (urgente)",
                     5:"deja ahora (urgente)"}},
    16  :   {"eng": {0:"fast (not urgent)",
                     1:"faster (not urgent)",
                     2:"quickly (urgent)"},
             "ita": {0:"veloce (non urgente)",
                     1:"più veloce (non urgente)",
                     2:"velocemente (no urgente)"},
             "esp": {0:"rapido (urgente)",
                     1:"más rapido (urgente)",
                     2:"rapidamente (urgente)"}},
    17  :   {"eng": {0:"slow (not urgent)",
                     1:"slower (not urgent)",
                     2:"slowly (not urgent)"},
             "ita": {0:"lento (non urgente)",
                     1:"più lento (non urgente)",
                     2:"lentamente (non urgente)"},
             "esp": {0:"lento (no urgente)",
                     1:"más lento (no urgente)",
                     2:"lentamente (no urgente)"}},
    18  :   {"eng": {0:"yes (not urgent)",
                     1:"okay (not urgent)"},
             "ita": {0:"si (non urgente)",
                     1:"va bene (non urgente)"},
             "esp": {0:"si (no urgente)",
                     1:"vale (no urgente)"}},
    19  :   {"eng": {0:"no (not urgent)"},
             "ita": {0:"no (non urgente)"},
             "esp": {0:"no (no urgente)"}},
    20  :   {"eng": {0:"maybe (not urgent)",
                     1:"i don't know (not urgent)"},
             "ita": {0:"forse (non urgente)",
                     1:"non lo so (non urgente)"},
             "esp": {0:"tal vez (no urgente)",
                     1:"no sé (no urgente)"}},
    21  :   {"eng": {0:"help me (not urgent)"},
             "ita": {0:"aiutami (non urgente)"},
             "esp": {0:"ayùdame (no urgente)"}},
    22  :   {"eng": {0:"help me (urgent)",
                     1:"help me immediately (urgent)",
                     2:"help me now (urgent)",
                     3:"help me quickly (urgent)"},
             "ita": {0:"aiutami (urgente)",
                     1:"aiutami immediatamente (urgente)",
                     2:"aiutami ora (urgente)"},
             "esp": {0:"ayùdame (urgente)",
                     1:"ayùdame inmediatamente (urgente)",
                     2:"ayùdame ahora (urgente)"}}
}