# Identify the complete Entity/topic name (UNISA.SpeechGestureAnalysis.Speech)
string id
# Identify the Entity/topic type (Speech)
string type
#Two-integer timestamp that is expressed as:
# * timestamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * timestamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
string timestamp
# Show the status information
string status