; Auto-generated. Do not edit!


(cl:in-package speech_pkg-msg)


;//! \htmlinclude IntentGoal.msg.html

(cl:defclass <IntentGoal> (roslisp-msg-protocol:ros-message)
  ((intent
    :reader intent
    :initarg :intent
    :type cl:fixnum
    :initform 0))
)

(cl:defclass IntentGoal (<IntentGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IntentGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IntentGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name speech_pkg-msg:<IntentGoal> is deprecated: use speech_pkg-msg:IntentGoal instead.")))

(cl:ensure-generic-function 'intent-val :lambda-list '(m))
(cl:defmethod intent-val ((m <IntentGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader speech_pkg-msg:intent-val is deprecated.  Use speech_pkg-msg:intent instead.")
  (intent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IntentGoal>) ostream)
  "Serializes a message object of type '<IntentGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'intent)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IntentGoal>) istream)
  "Deserializes a message object of type '<IntentGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'intent)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IntentGoal>)))
  "Returns string type for a message object of type '<IntentGoal>"
  "speech_pkg/IntentGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IntentGoal)))
  "Returns string type for a message object of type 'IntentGoal"
  "speech_pkg/IntentGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IntentGoal>)))
  "Returns md5sum for a message object of type '<IntentGoal>"
  "cd0d52ef49a3bd3e6f56af43958b6723")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IntentGoal)))
  "Returns md5sum for a message object of type 'IntentGoal"
  "cd0d52ef49a3bd3e6f56af43958b6723")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IntentGoal>)))
  "Returns full string definition for message of type '<IntentGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The ID of the intent~%uint8 intent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IntentGoal)))
  "Returns full string definition for message of type 'IntentGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The ID of the intent~%uint8 intent~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IntentGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IntentGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'IntentGoal
    (cl:cons ':intent (intent msg))
))
