// Generated by gencpp from file speech_pkg/ClassificationMSI.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_CLASSIFICATIONMSI_H
#define SPEECH_PKG_MESSAGE_CLASSIFICATIONMSI_H

#include <ros/service_traits.h>


#include <speech_pkg/ClassificationMSIRequest.h>
#include <speech_pkg/ClassificationMSIResponse.h>


namespace speech_pkg
{

struct ClassificationMSI
{

typedef ClassificationMSIRequest Request;
typedef ClassificationMSIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClassificationMSI
} // namespace speech_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speech_pkg::ClassificationMSI > {
  static const char* value()
  {
    return "86bdd504432c8f4cd29e4aa496bd70a0";
  }

  static const char* value(const ::speech_pkg::ClassificationMSI&) { return value(); }
};

template<>
struct DataType< ::speech_pkg::ClassificationMSI > {
  static const char* value()
  {
    return "speech_pkg/ClassificationMSI";
  }

  static const char* value(const ::speech_pkg::ClassificationMSI&) { return value(); }
};


// service_traits::MD5Sum< ::speech_pkg::ClassificationMSIRequest> should match
// service_traits::MD5Sum< ::speech_pkg::ClassificationMSI >
template<>
struct MD5Sum< ::speech_pkg::ClassificationMSIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::ClassificationMSI >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationMSIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::ClassificationMSIRequest> should match
// service_traits::DataType< ::speech_pkg::ClassificationMSI >
template<>
struct DataType< ::speech_pkg::ClassificationMSIRequest>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::ClassificationMSI >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationMSIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speech_pkg::ClassificationMSIResponse> should match
// service_traits::MD5Sum< ::speech_pkg::ClassificationMSI >
template<>
struct MD5Sum< ::speech_pkg::ClassificationMSIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::ClassificationMSI >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationMSIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::ClassificationMSIResponse> should match
// service_traits::DataType< ::speech_pkg::ClassificationMSI >
template<>
struct DataType< ::speech_pkg::ClassificationMSIResponse>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::ClassificationMSI >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationMSIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_CLASSIFICATIONMSI_H
