// Generated by gencpp from file speech_pkg/IntentIRI.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_INTENTIRI_H
#define SPEECH_PKG_MESSAGE_INTENTIRI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace speech_pkg
{
template <class ContainerAllocator>
struct IntentIRI_
{
  typedef IntentIRI_<ContainerAllocator> Type;

  IntentIRI_()
    : header()
    , fsr_values()
    , sw_values()  {
      fsr_values.assign(0.0);

      sw_values.assign(false);
  }
  IntentIRI_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fsr_values()
    , sw_values()  {
  (void)_alloc;
      fsr_values.assign(0.0);

      sw_values.assign(false);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 5>  _fsr_values_type;
  _fsr_values_type fsr_values;

   typedef boost::array<uint8_t, 5>  _sw_values_type;
  _sw_values_type sw_values;





  typedef boost::shared_ptr< ::speech_pkg::IntentIRI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_pkg::IntentIRI_<ContainerAllocator> const> ConstPtr;

}; // struct IntentIRI_

typedef ::speech_pkg::IntentIRI_<std::allocator<void> > IntentIRI;

typedef boost::shared_ptr< ::speech_pkg::IntentIRI > IntentIRIPtr;
typedef boost::shared_ptr< ::speech_pkg::IntentIRI const> IntentIRIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_pkg::IntentIRI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_pkg::IntentIRI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech_pkg::IntentIRI_<ContainerAllocator1> & lhs, const ::speech_pkg::IntentIRI_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fsr_values == rhs.fsr_values &&
    lhs.sw_values == rhs.sw_values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech_pkg::IntentIRI_<ContainerAllocator1> & lhs, const ::speech_pkg::IntentIRI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::IntentIRI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::IntentIRI_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::IntentIRI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::IntentIRI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::IntentIRI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::IntentIRI_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_pkg::IntentIRI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62dc5f03f1a505652316491d926de860";
  }

  static const char* value(const ::speech_pkg::IntentIRI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62dc5f03f1a50565ULL;
  static const uint64_t static_value2 = 0x2316491d926de860ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_pkg::IntentIRI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_pkg/IntentIRI";
  }

  static const char* value(const ::speech_pkg::IntentIRI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_pkg::IntentIRI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[5] fsr_values\n"
"bool[5] sw_values\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::speech_pkg::IntentIRI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_pkg::IntentIRI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fsr_values);
      stream.next(m.sw_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntentIRI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_pkg::IntentIRI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_pkg::IntentIRI_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fsr_values[]" << std::endl;
    for (size_t i = 0; i < v.fsr_values.size(); ++i)
    {
      s << indent << "  fsr_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.fsr_values[i]);
    }
    s << indent << "sw_values[]" << std::endl;
    for (size_t i = 0; i < v.sw_values.size(); ++i)
    {
      s << indent << "  sw_values[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.sw_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_INTENTIRI_H
