// Generated by gencpp from file speech_pkg/SCR.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_SCR_H
#define SPEECH_PKG_MESSAGE_SCR_H

#include <ros/service_traits.h>


#include <speech_pkg/SCRRequest.h>
#include <speech_pkg/SCRResponse.h>


namespace speech_pkg
{

struct SCR
{

typedef SCRRequest Request;
typedef SCRResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SCR
} // namespace speech_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speech_pkg::SCR > {
  static const char* value()
  {
    return "896849feb7849138871db12c46e37d25";
  }

  static const char* value(const ::speech_pkg::SCR&) { return value(); }
};

template<>
struct DataType< ::speech_pkg::SCR > {
  static const char* value()
  {
    return "speech_pkg/SCR";
  }

  static const char* value(const ::speech_pkg::SCR&) { return value(); }
};


// service_traits::MD5Sum< ::speech_pkg::SCRRequest> should match
// service_traits::MD5Sum< ::speech_pkg::SCR >
template<>
struct MD5Sum< ::speech_pkg::SCRRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::SCR >::value();
  }
  static const char* value(const ::speech_pkg::SCRRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::SCRRequest> should match
// service_traits::DataType< ::speech_pkg::SCR >
template<>
struct DataType< ::speech_pkg::SCRRequest>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::SCR >::value();
  }
  static const char* value(const ::speech_pkg::SCRRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speech_pkg::SCRResponse> should match
// service_traits::MD5Sum< ::speech_pkg::SCR >
template<>
struct MD5Sum< ::speech_pkg::SCRResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::SCR >::value();
  }
  static const char* value(const ::speech_pkg::SCRResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::SCRResponse> should match
// service_traits::DataType< ::speech_pkg::SCR >
template<>
struct DataType< ::speech_pkg::SCRResponse>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::SCR >::value();
  }
  static const char* value(const ::speech_pkg::SCRResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_SCR_H
