// Generated by gencpp from file speech_pkg/SpeechManager.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_SPEECHMANAGER_H
#define SPEECH_PKG_MESSAGE_SPEECHMANAGER_H

#include <ros/service_traits.h>


#include <speech_pkg/SpeechManagerRequest.h>
#include <speech_pkg/SpeechManagerResponse.h>


namespace speech_pkg
{

struct SpeechManager
{

typedef SpeechManagerRequest Request;
typedef SpeechManagerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeechManager
} // namespace speech_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speech_pkg::SpeechManager > {
  static const char* value()
  {
    return "426efa73e6c8d460d7543a8bf442644f";
  }

  static const char* value(const ::speech_pkg::SpeechManager&) { return value(); }
};

template<>
struct DataType< ::speech_pkg::SpeechManager > {
  static const char* value()
  {
    return "speech_pkg/SpeechManager";
  }

  static const char* value(const ::speech_pkg::SpeechManager&) { return value(); }
};


// service_traits::MD5Sum< ::speech_pkg::SpeechManagerRequest> should match
// service_traits::MD5Sum< ::speech_pkg::SpeechManager >
template<>
struct MD5Sum< ::speech_pkg::SpeechManagerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::SpeechManager >::value();
  }
  static const char* value(const ::speech_pkg::SpeechManagerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::SpeechManagerRequest> should match
// service_traits::DataType< ::speech_pkg::SpeechManager >
template<>
struct DataType< ::speech_pkg::SpeechManagerRequest>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::SpeechManager >::value();
  }
  static const char* value(const ::speech_pkg::SpeechManagerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speech_pkg::SpeechManagerResponse> should match
// service_traits::MD5Sum< ::speech_pkg::SpeechManager >
template<>
struct MD5Sum< ::speech_pkg::SpeechManagerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::SpeechManager >::value();
  }
  static const char* value(const ::speech_pkg::SpeechManagerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::SpeechManagerResponse> should match
// service_traits::DataType< ::speech_pkg::SpeechManager >
template<>
struct DataType< ::speech_pkg::SpeechManagerResponse>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::SpeechManager >::value();
  }
  static const char* value(const ::speech_pkg::SpeechManagerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_SPEECHMANAGER_H
