sudo: required

stages:
  - name: test
  - name: deploy
    if: (type NOT IN (pull_request)) AND branch IN (master)

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "Unit Tests"

      language: python
      python: "2.7"
      cache: pip

      before_install:
        - git submodule update --init --recursive

      install:
        - pip install -r requirements.txt

      script:
        - export PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}/firos/include/FiwareObjectConverter"
        - cd firos && python -m unittest discover


    - stage: test
      name: "Documentation Tests"
      language: node_js
      node_js: 10

      install:
        - npm install

      script:
        - npm run lint:md
        - npm run lint:text


    - stage: deploy
      name: "Docker build and push"
      language: ruby
      on:
        branch: master

      services:
        - docker

      script:
        - docker build -f ./docker/Dockerfile --tag fhgiml130/firos:latest .
        - docker-compose -f ./docker/docker-compose.yml build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push fhgiml130/firos:latest
