# coding=utf-8
""" DEMO_CMD_ENG = {
    0: "Increase the height",
    1: "Decrease the height",
    2: "Start",
    3: "Release",
    4: "Bring me the gun screwdriver",
    5: "Take the gun screwdriver",
    6: "Bring me the windows control panel",
    7: "Take the windows control panel",
    8: "No command"
}

DEMO_CMD_ITA = {
    0: "Piu alto",
    1: "Piu basso",
    2: "Start",
    3: "Rilascia",
    4: "Portami l'avvitatore elettrico",
    5: "Prendi l'avvitatore elettrico",
    6: "Portami la mostrina comandi",
    7: "Prendi la mostrina comandi",
    8: "Nessun comando"
} """

#"""
DEMO_CMD_ENG = {
    0: "Increase the illumination",
    1: "Decrease the illumination",
    2: "Increase the height",
    3: "Decrease the height",
    4: "Increase the inclination",
    5: "Decrease the inclination",
    6: "Bring me the gun screwdriver",
    7: "Take the gun screwdriver",
    8: "Bring me the elbow screwdriver",
    9: "Take the elbow screwdriver",
    10: "Bring me the hammer",
    11: "Take the hammer",
    12: "Bring me the screwdriver",
    13: "Take the screwdriver",
    14: "Bring me the lever",
    15: "Take the lever",
    16: "Bring me the windows control panel",
    17: "Take the windows control panel",
    18: "Bring me the rearview mirror",
    19: "Take the rearview mirror",
    20: "Release",
    21: "Come here",
    22: "Go",
    23: "Start",
    24: "Stop",
    25: "Move to the right",
    26: "Move to the left",
    27: "Move up",
    28: "Move down",
    29: "Move forward",
    30: "Move backward",
    31: "No command"
}

DEMO_CMD_ITA = {
    0: "Più luce",
    1: "Meno luce",
    2: "Più alto",
    3: "Più basso",
    4: "Più inclinato",
    5: "Meno inclinato",
    6: "Portami l'avvitatore elettrico",
    7: "Prendi l'avvitatore elettrico",
    8: "Portami l'avvitatore a gomito",
    9: "Prendi l'avvitatore a gomito",
    10: "Portami il martello",
    11: "Prendi il martello",
    12: "Portami il cacciavite",
    13: "Prendi il cacciavite",
    14: "Portami la leva",
    15: "Prendi la leva",
    16: "Portami la mostrina comandi",
    17: "Prendi la mostrina comandi",
    18: "Portami lo specchietto retrovisore",
    19: "Prendi lo specchietto retrovisore",
    20: "Rilascia",
    21: "Vieni",
    22: "Libero",
    23: "Start",
    24: "Stop",
    25: "Vai a destra",
    26: "Vai a sinistra",
    27: "Vai su",
    28: "Vai giù",
    29: "Vai avanti",
    30: "Vai indietro",
    31: "Nessun comando"
}
#"""