COMMANDS = {
    "eng":{
        0: "Increase the height",
        1: "Decrease the height",
        2: "Increase the inclination",
        3: "Decrease the inclination",
        4: "Increase the illumination",
        5: "Decrease the illumination",
        6: "Increase the illumination one",
        7: "Decrease the illumination one",
        8: "Increase the illumination two",
        9: "Decrease the illumination two",
        10:"Bring me the gun screwdriver",
        11:"Take the gun screwdriver",
        12:"Bring me the elbow screwdriver one",
        13:"Take the elbow screwdriver one",
        14:"Bring me the elbow screwdriver two",
        15:"Take the elbow screwdriver two",
        16:"Bring me the windows control panel",
        17:"Take the windows control panel",
        18:"Bring me the window frame",
        19:"Take the window frame",
        20:"Bring me the speaker",
        21:"Take the speaker", 
        22:"Bring me the object holder",
        23:"Take the object holder",
        24:"Bring me the speaker frame",
        25:"Take the speaker frame",
        26:"Open",
        27:"Close",
        28:"Release" 
    },
    "ita":{
        0: "Piu alto",
        1: "Piu basso",
        2: "Piu inclinato",
        3: "Meno inclinato",
        4: "Piu luce",
        5: "Meno luce",
        6: "Piu luce uno",
        7: "Meno luce uno",
        8: "Piu luce due",
        9: "Meno luce due",
        10:"Portami l avvitatore elettrico",
        11:"Prendi l avvitatore elettrico",
        12:"Portami l avvitatore a gomito uno",
        13:"Prendi l avvitatore a gomito uno",
        14:"Portami l avvitatore a gomito due",
        15:"Prendi l avvitatore a gomito due",
        16:"Portami la mostrina comandi",
        17:"Prendi la mostrina comandi",
        18:"Portami il voletto",
        19:"Prendi il voletto",
        20:"Portami l altoparlante",
        21:"Prendi l altoparlante", 
        22:"Portami il porta oggetti",
        23:"Prendi il porta oggetti",
        24:"Portami il telaio dell altoparlante",
        25:"Prendi il telaio altoparlante",
        26:"Apri",
        27:"Chiudi",
        28:"Rilascia" 
    }
}

ADD_COMMANDS = {
    "eng":{
        12:"Bring me the elbow screwdriver one",
        13:"Take the elbow screwdriver one",
        14:"Bring me the elbow screwdriver two",
        15:"Take the elbow screwdriver two",
        24:"Bring me the speaker frame",
        25:"Take the speaker frame",
    },
    "ita":{
        12:"Portami l avvitatore a gomito uno",
        13:"Prendi l avvitatore a gomito uno",
        14:"Portami l avvitatore a gomito due",
        15:"Prendi l avvitatore a gomito due",
        24:"Portami il telaio dell altoparlante",
        25:"Prendi il telaio altoparlante"
    }
}