(cl:defpackage speech_pkg-srv
  (:use )
  (:export
   "SCR"
   "<SCR-REQUEST>"
   "SCR-REQUEST"
   "<SCR-RESPONSE>"
   "SCR-RESPONSE"
   "SPEECHMANAGER"
   "<SPEECHMANAGER-REQUEST>"
   "SPEECHMANAGER-REQUEST"
   "<SPEECHMANAGER-RESPONSE>"
   "SPEECHMANAGER-RESPONSE"
  ))

