// Generated by gencpp from file iri_object_transportation_msgs/wrenchStampedArray.msg
// DO NOT EDIT!


#ifndef IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_WRENCHSTAMPEDARRAY_H
#define IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_WRENCHSTAMPEDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/WrenchStamped.h>

namespace iri_object_transportation_msgs
{
template <class ContainerAllocator>
struct wrenchStampedArray_
{
  typedef wrenchStampedArray_<ContainerAllocator> Type;

  wrenchStampedArray_()
    : header()
    , wrench_array()  {
    }
  wrenchStampedArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , wrench_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::WrenchStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >::other >  _wrench_array_type;
  _wrench_array_type wrench_array;





  typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> const> ConstPtr;

}; // struct wrenchStampedArray_

typedef ::iri_object_transportation_msgs::wrenchStampedArray_<std::allocator<void> > wrenchStampedArray;

typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedArray > wrenchStampedArrayPtr;
typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedArray const> wrenchStampedArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.wrench_array == rhs.wrench_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_object_transportation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc21e36c114cf78455cddabb6d297980";
  }

  static const char* value(const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc21e36c114cf784ULL;
  static const uint64_t static_value2 = 0x55cddabb6d297980ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_object_transportation_msgs/wrenchStampedArray";
  }

  static const char* value(const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/WrenchStamped[] wrench_array\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/WrenchStamped\n"
"# A wrench with reference coordinate frame and timestamp\n"
"Header header\n"
"Wrench wrench\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.wrench_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wrenchStampedArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_object_transportation_msgs::wrenchStampedArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wrench_array[]" << std::endl;
    for (size_t i = 0; i < v.wrench_array.size(); ++i)
    {
      s << indent << "  wrench_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.wrench_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_WRENCHSTAMPEDARRAY_H
