// Generated by gencpp from file iri_object_transportation_msgs/wrenchStampedWithCoeff.msg
// DO NOT EDIT!


#ifndef IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_WRENCHSTAMPEDWITHCOEFF_H
#define IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_WRENCHSTAMPEDWITHCOEFF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/WrenchStamped.h>

namespace iri_object_transportation_msgs
{
template <class ContainerAllocator>
struct wrenchStampedWithCoeff_
{
  typedef wrenchStampedWithCoeff_<ContainerAllocator> Type;

  wrenchStampedWithCoeff_()
    : external_force()
    , coefficient(0.0)  {
    }
  wrenchStampedWithCoeff_(const ContainerAllocator& _alloc)
    : external_force(_alloc)
    , coefficient(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::WrenchStamped_<ContainerAllocator>  _external_force_type;
  _external_force_type external_force;

   typedef float _coefficient_type;
  _coefficient_type coefficient;





  typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> const> ConstPtr;

}; // struct wrenchStampedWithCoeff_

typedef ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<std::allocator<void> > wrenchStampedWithCoeff;

typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedWithCoeff > wrenchStampedWithCoeffPtr;
typedef boost::shared_ptr< ::iri_object_transportation_msgs::wrenchStampedWithCoeff const> wrenchStampedWithCoeffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator2> & rhs)
{
  return lhs.external_force == rhs.external_force &&
    lhs.coefficient == rhs.coefficient;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator1> & lhs, const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iri_object_transportation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f94a203c7491df5185f74fa3237bfc7";
  }

  static const char* value(const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f94a203c7491df5ULL;
  static const uint64_t static_value2 = 0x185f74fa3237bfc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iri_object_transportation_msgs/wrenchStampedWithCoeff";
  }

  static const char* value(const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/WrenchStamped external_force\n"
"float32 coefficient\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/WrenchStamped\n"
"# A wrench with reference coordinate frame and timestamp\n"
"Header header\n"
"Wrench wrench\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.external_force);
      stream.next(m.coefficient);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wrenchStampedWithCoeff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iri_object_transportation_msgs::wrenchStampedWithCoeff_<ContainerAllocator>& v)
  {
    s << indent << "external_force: ";
    s << std::endl;
    Printer< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.external_force);
    s << indent << "coefficient: ";
    Printer<float>::stream(s, indent + "  ", v.coefficient);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRI_OBJECT_TRANSPORTATION_MSGS_MESSAGE_WRENCHSTAMPEDWITHCOEFF_H
