// Generated by gencpp from file speech_pkg/Classification.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_CLASSIFICATION_H
#define SPEECH_PKG_MESSAGE_CLASSIFICATION_H

#include <ros/service_traits.h>


#include <speech_pkg/ClassificationRequest.h>
#include <speech_pkg/ClassificationResponse.h>


namespace speech_pkg
{

struct Classification
{

typedef ClassificationRequest Request;
typedef ClassificationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Classification
} // namespace speech_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speech_pkg::Classification > {
  static const char* value()
  {
    return "896849feb7849138871db12c46e37d25";
  }

  static const char* value(const ::speech_pkg::Classification&) { return value(); }
};

template<>
struct DataType< ::speech_pkg::Classification > {
  static const char* value()
  {
    return "speech_pkg/Classification";
  }

  static const char* value(const ::speech_pkg::Classification&) { return value(); }
};


// service_traits::MD5Sum< ::speech_pkg::ClassificationRequest> should match
// service_traits::MD5Sum< ::speech_pkg::Classification >
template<>
struct MD5Sum< ::speech_pkg::ClassificationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::Classification >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::ClassificationRequest> should match
// service_traits::DataType< ::speech_pkg::Classification >
template<>
struct DataType< ::speech_pkg::ClassificationRequest>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::Classification >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speech_pkg::ClassificationResponse> should match
// service_traits::MD5Sum< ::speech_pkg::Classification >
template<>
struct MD5Sum< ::speech_pkg::ClassificationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::Classification >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::ClassificationResponse> should match
// service_traits::DataType< ::speech_pkg::Classification >
template<>
struct DataType< ::speech_pkg::ClassificationResponse>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::Classification >::value();
  }
  static const char* value(const ::speech_pkg::ClassificationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_CLASSIFICATION_H
