// Generated by gencpp from file speech_pkg/Manager.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_MANAGER_H
#define SPEECH_PKG_MESSAGE_MANAGER_H

#include <ros/service_traits.h>


#include <speech_pkg/ManagerRequest.h>
#include <speech_pkg/ManagerResponse.h>


namespace speech_pkg
{

struct Manager
{

typedef ManagerRequest Request;
typedef ManagerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Manager
} // namespace speech_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speech_pkg::Manager > {
  static const char* value()
  {
    return "426efa73e6c8d460d7543a8bf442644f";
  }

  static const char* value(const ::speech_pkg::Manager&) { return value(); }
};

template<>
struct DataType< ::speech_pkg::Manager > {
  static const char* value()
  {
    return "speech_pkg/Manager";
  }

  static const char* value(const ::speech_pkg::Manager&) { return value(); }
};


// service_traits::MD5Sum< ::speech_pkg::ManagerRequest> should match
// service_traits::MD5Sum< ::speech_pkg::Manager >
template<>
struct MD5Sum< ::speech_pkg::ManagerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::Manager >::value();
  }
  static const char* value(const ::speech_pkg::ManagerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::ManagerRequest> should match
// service_traits::DataType< ::speech_pkg::Manager >
template<>
struct DataType< ::speech_pkg::ManagerRequest>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::Manager >::value();
  }
  static const char* value(const ::speech_pkg::ManagerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speech_pkg::ManagerResponse> should match
// service_traits::MD5Sum< ::speech_pkg::Manager >
template<>
struct MD5Sum< ::speech_pkg::ManagerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::Manager >::value();
  }
  static const char* value(const ::speech_pkg::ManagerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::ManagerResponse> should match
// service_traits::DataType< ::speech_pkg::Manager >
template<>
struct DataType< ::speech_pkg::ManagerResponse>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::Manager >::value();
  }
  static const char* value(const ::speech_pkg::ManagerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_MANAGER_H
