// Generated by gencpp from file speech_pkg/SpeechData.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_SPEECHDATA_H
#define SPEECH_PKG_MESSAGE_SPEECHDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech_pkg
{
template <class ContainerAllocator>
struct SpeechData_
{
  typedef SpeechData_<ContainerAllocator> Type;

  SpeechData_()
    : data()
    , doa(0)
    , start_time(0.0)
    , end_time(0.0)  {
    }
  SpeechData_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , doa(0)
    , start_time(0.0)
    , end_time(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _data_type;
  _data_type data;

   typedef int16_t _doa_type;
  _doa_type doa;

   typedef double _start_time_type;
  _start_time_type start_time;

   typedef double _end_time_type;
  _end_time_type end_time;





  typedef boost::shared_ptr< ::speech_pkg::SpeechData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_pkg::SpeechData_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechData_

typedef ::speech_pkg::SpeechData_<std::allocator<void> > SpeechData;

typedef boost::shared_ptr< ::speech_pkg::SpeechData > SpeechDataPtr;
typedef boost::shared_ptr< ::speech_pkg::SpeechData const> SpeechDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_pkg::SpeechData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_pkg::SpeechData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech_pkg::SpeechData_<ContainerAllocator1> & lhs, const ::speech_pkg::SpeechData_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.doa == rhs.doa &&
    lhs.start_time == rhs.start_time &&
    lhs.end_time == rhs.end_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech_pkg::SpeechData_<ContainerAllocator1> & lhs, const ::speech_pkg::SpeechData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::SpeechData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::SpeechData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::SpeechData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::SpeechData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::SpeechData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::SpeechData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_pkg::SpeechData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2d258c719b9a4af008aff70e592c3a6";
  }

  static const char* value(const ::speech_pkg::SpeechData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2d258c719b9a4afULL;
  static const uint64_t static_value2 = 0x008aff70e592c3a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_pkg::SpeechData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_pkg/SpeechData";
  }

  static const char* value(const ::speech_pkg::SpeechData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_pkg::SpeechData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] data\n"
"int16 doa\n"
"float64 start_time\n"
"float64 end_time\n"
;
  }

  static const char* value(const ::speech_pkg::SpeechData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_pkg::SpeechData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.doa);
      stream.next(m.start_time);
      stream.next(m.end_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_pkg::SpeechData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_pkg::SpeechData_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "doa: ";
    Printer<int16_t>::stream(s, indent + "  ", v.doa);
    s << indent << "start_time: ";
    Printer<double>::stream(s, indent + "  ", v.start_time);
    s << indent << "end_time: ";
    Printer<double>::stream(s, indent + "  ", v.end_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_SPEECHDATA_H
