// Generated by gencpp from file speech_pkg/SystemHealth.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_SYSTEMHEALTH_H
#define SPEECH_PKG_MESSAGE_SYSTEMHEALTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech_pkg
{
template <class ContainerAllocator>
struct SystemHealth_
{
  typedef SystemHealth_<ContainerAllocator> Type;

  SystemHealth_()
    : id()
    , type()
    , timestamp()
    , status()  {
    }
  SystemHealth_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , type(_alloc)
    , timestamp(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _timestamp_type;
  _timestamp_type timestamp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::speech_pkg::SystemHealth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_pkg::SystemHealth_<ContainerAllocator> const> ConstPtr;

}; // struct SystemHealth_

typedef ::speech_pkg::SystemHealth_<std::allocator<void> > SystemHealth;

typedef boost::shared_ptr< ::speech_pkg::SystemHealth > SystemHealthPtr;
typedef boost::shared_ptr< ::speech_pkg::SystemHealth const> SystemHealthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_pkg::SystemHealth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_pkg::SystemHealth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech_pkg::SystemHealth_<ContainerAllocator1> & lhs, const ::speech_pkg::SystemHealth_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.timestamp == rhs.timestamp &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech_pkg::SystemHealth_<ContainerAllocator1> & lhs, const ::speech_pkg::SystemHealth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::SystemHealth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::SystemHealth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::SystemHealth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::SystemHealth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::SystemHealth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::SystemHealth_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_pkg::SystemHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ca1632d366bfbb66f928108e6362e1d";
  }

  static const char* value(const ::speech_pkg::SystemHealth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ca1632d366bfbb6ULL;
  static const uint64_t static_value2 = 0x6f928108e6362e1dULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_pkg::SystemHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_pkg/SystemHealth";
  }

  static const char* value(const ::speech_pkg::SystemHealth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_pkg::SystemHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Identify the complete Entity/topic name (UNISA.SpeechGestureAnalysis.Speech)\n"
"string id\n"
"# Identify the Entity/topic type (Speech)\n"
"string type\n"
"#Two-integer timestamp that is expressed as:\n"
"# * timestamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * timestamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"string timestamp\n"
"# Show the status information\n"
"string status\n"
;
  }

  static const char* value(const ::speech_pkg::SystemHealth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_pkg::SystemHealth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.timestamp);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemHealth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_pkg::SystemHealth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_pkg::SystemHealth_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "timestamp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.timestamp);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_SYSTEMHEALTH_H
