// Generated by gencpp from file speech_pkg/TalkerResponse.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_TALKERRESPONSE_H
#define SPEECH_PKG_MESSAGE_TALKERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech_pkg
{
template <class ContainerAllocator>
struct TalkerResponse_
{
  typedef TalkerResponse_<ContainerAllocator> Type;

  TalkerResponse_()
    : flag(false)  {
    }
  TalkerResponse_(const ContainerAllocator& _alloc)
    : flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::speech_pkg::TalkerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_pkg::TalkerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TalkerResponse_

typedef ::speech_pkg::TalkerResponse_<std::allocator<void> > TalkerResponse;

typedef boost::shared_ptr< ::speech_pkg::TalkerResponse > TalkerResponsePtr;
typedef boost::shared_ptr< ::speech_pkg::TalkerResponse const> TalkerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_pkg::TalkerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_pkg::TalkerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech_pkg::TalkerResponse_<ContainerAllocator1> & lhs, const ::speech_pkg::TalkerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech_pkg::TalkerResponse_<ContainerAllocator1> & lhs, const ::speech_pkg::TalkerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::TalkerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::TalkerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::TalkerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24842bc754e0f5cc982338eca1269251";
  }

  static const char* value(const ::speech_pkg::TalkerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24842bc754e0f5ccULL;
  static const uint64_t static_value2 = 0x982338eca1269251ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_pkg/TalkerResponse";
  }

  static const char* value(const ::speech_pkg::TalkerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag\n"
;
  }

  static const char* value(const ::speech_pkg::TalkerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TalkerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_pkg::TalkerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_pkg::TalkerResponse_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_TALKERRESPONSE_H
