// Generated by gencpp from file speech_pkg/TalkerRequest.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_TALKERREQUEST_H
#define SPEECH_PKG_MESSAGE_TALKERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech_pkg
{
template <class ContainerAllocator>
struct TalkerRequest_
{
  typedef TalkerRequest_<ContainerAllocator> Type;

  TalkerRequest_()
    : cmd(0)
    , probs()  {
    }
  TalkerRequest_(const ContainerAllocator& _alloc)
    : cmd(0)
    , probs(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _cmd_type;
  _cmd_type cmd;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _probs_type;
  _probs_type probs;





  typedef boost::shared_ptr< ::speech_pkg::TalkerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_pkg::TalkerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TalkerRequest_

typedef ::speech_pkg::TalkerRequest_<std::allocator<void> > TalkerRequest;

typedef boost::shared_ptr< ::speech_pkg::TalkerRequest > TalkerRequestPtr;
typedef boost::shared_ptr< ::speech_pkg::TalkerRequest const> TalkerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_pkg::TalkerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_pkg::TalkerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech_pkg::TalkerRequest_<ContainerAllocator1> & lhs, const ::speech_pkg::TalkerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.probs == rhs.probs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech_pkg::TalkerRequest_<ContainerAllocator1> & lhs, const ::speech_pkg::TalkerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_pkg::TalkerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_pkg::TalkerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_pkg::TalkerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b530570166a9025ca374b3a6285b3928";
  }

  static const char* value(const ::speech_pkg::TalkerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb530570166a9025cULL;
  static const uint64_t static_value2 = 0xa374b3a6285b3928ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_pkg/TalkerRequest";
  }

  static const char* value(const ::speech_pkg::TalkerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 cmd\n"
"float32[] probs\n"
;
  }

  static const char* value(const ::speech_pkg::TalkerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.probs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TalkerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_pkg::TalkerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_pkg::TalkerRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "probs[]" << std::endl;
    for (size_t i = 0; i < v.probs.size(); ++i)
    {
      s << indent << "  probs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.probs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_TALKERREQUEST_H
