// Generated by gencpp from file speech_pkg/Talker.msg
// DO NOT EDIT!


#ifndef SPEECH_PKG_MESSAGE_TALKER_H
#define SPEECH_PKG_MESSAGE_TALKER_H

#include <ros/service_traits.h>


#include <speech_pkg/TalkerRequest.h>
#include <speech_pkg/TalkerResponse.h>


namespace speech_pkg
{

struct Talker
{

typedef TalkerRequest Request;
typedef TalkerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Talker
} // namespace speech_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speech_pkg::Talker > {
  static const char* value()
  {
    return "b542a23d9f2300b346a3653dfa7b8829";
  }

  static const char* value(const ::speech_pkg::Talker&) { return value(); }
};

template<>
struct DataType< ::speech_pkg::Talker > {
  static const char* value()
  {
    return "speech_pkg/Talker";
  }

  static const char* value(const ::speech_pkg::Talker&) { return value(); }
};


// service_traits::MD5Sum< ::speech_pkg::TalkerRequest> should match
// service_traits::MD5Sum< ::speech_pkg::Talker >
template<>
struct MD5Sum< ::speech_pkg::TalkerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::Talker >::value();
  }
  static const char* value(const ::speech_pkg::TalkerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::TalkerRequest> should match
// service_traits::DataType< ::speech_pkg::Talker >
template<>
struct DataType< ::speech_pkg::TalkerRequest>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::Talker >::value();
  }
  static const char* value(const ::speech_pkg::TalkerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speech_pkg::TalkerResponse> should match
// service_traits::MD5Sum< ::speech_pkg::Talker >
template<>
struct MD5Sum< ::speech_pkg::TalkerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speech_pkg::Talker >::value();
  }
  static const char* value(const ::speech_pkg::TalkerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speech_pkg::TalkerResponse> should match
// service_traits::DataType< ::speech_pkg::Talker >
template<>
struct DataType< ::speech_pkg::TalkerResponse>
{
  static const char* value()
  {
    return DataType< ::speech_pkg::Talker >::value();
  }
  static const char* value(const ::speech_pkg::TalkerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECH_PKG_MESSAGE_TALKER_H
