# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from iri_object_transportation_msgs/localForcesSFM.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import iri_object_transportation_msgs.msg
import std_msgs.msg

class localForcesSFM(genpy.Message):
  _md5sum = "f1cd253465458d5a2c178d26ef88bcf8"
  _type = "iri_object_transportation_msgs/localForcesSFM"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/WrenchStamped goal_force
geometry_msgs/WrenchStamped attractor_force
iri_object_transportation_msgs/wrenchStampedArray obstacles_forces
geometry_msgs/WrenchStamped total_force

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/WrenchStamped
# A wrench with reference coordinate frame and timestamp
Header header
Wrench wrench

================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: iri_object_transportation_msgs/wrenchStampedArray
Header header
geometry_msgs/WrenchStamped[] wrench_array
"""
  __slots__ = ['header','goal_force','attractor_force','obstacles_forces','total_force']
  _slot_types = ['std_msgs/Header','geometry_msgs/WrenchStamped','geometry_msgs/WrenchStamped','iri_object_transportation_msgs/wrenchStampedArray','geometry_msgs/WrenchStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,goal_force,attractor_force,obstacles_forces,total_force

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(localForcesSFM, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_force is None:
        self.goal_force = geometry_msgs.msg.WrenchStamped()
      if self.attractor_force is None:
        self.attractor_force = geometry_msgs.msg.WrenchStamped()
      if self.obstacles_forces is None:
        self.obstacles_forces = iri_object_transportation_msgs.msg.wrenchStampedArray()
      if self.total_force is None:
        self.total_force = geometry_msgs.msg.WrenchStamped()
    else:
      self.header = std_msgs.msg.Header()
      self.goal_force = geometry_msgs.msg.WrenchStamped()
      self.attractor_force = geometry_msgs.msg.WrenchStamped()
      self.obstacles_forces = iri_object_transportation_msgs.msg.wrenchStampedArray()
      self.total_force = geometry_msgs.msg.WrenchStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.goal_force.header.seq, _x.goal_force.header.stamp.secs, _x.goal_force.header.stamp.nsecs))
      _x = self.goal_force.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d3I().pack(_x.goal_force.wrench.force.x, _x.goal_force.wrench.force.y, _x.goal_force.wrench.force.z, _x.goal_force.wrench.torque.x, _x.goal_force.wrench.torque.y, _x.goal_force.wrench.torque.z, _x.attractor_force.header.seq, _x.attractor_force.header.stamp.secs, _x.attractor_force.header.stamp.nsecs))
      _x = self.attractor_force.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d3I().pack(_x.attractor_force.wrench.force.x, _x.attractor_force.wrench.force.y, _x.attractor_force.wrench.force.z, _x.attractor_force.wrench.torque.x, _x.attractor_force.wrench.torque.y, _x.attractor_force.wrench.torque.z, _x.obstacles_forces.header.seq, _x.obstacles_forces.header.stamp.secs, _x.obstacles_forces.header.stamp.nsecs))
      _x = self.obstacles_forces.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.obstacles_forces.wrench_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacles_forces.wrench_array:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.wrench
        _v4 = _v3.force
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v5 = _v3.torque
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3I().pack(_x.total_force.header.seq, _x.total_force.header.stamp.secs, _x.total_force.header.stamp.nsecs))
      _x = self.total_force.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.total_force.wrench.force.x, _x.total_force.wrench.force.y, _x.total_force.wrench.force.z, _x.total_force.wrench.torque.x, _x.total_force.wrench.torque.y, _x.total_force.wrench.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_force is None:
        self.goal_force = geometry_msgs.msg.WrenchStamped()
      if self.attractor_force is None:
        self.attractor_force = geometry_msgs.msg.WrenchStamped()
      if self.obstacles_forces is None:
        self.obstacles_forces = iri_object_transportation_msgs.msg.wrenchStampedArray()
      if self.total_force is None:
        self.total_force = geometry_msgs.msg.WrenchStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.goal_force.header.seq, _x.goal_force.header.stamp.secs, _x.goal_force.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_force.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_force.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.goal_force.wrench.force.x, _x.goal_force.wrench.force.y, _x.goal_force.wrench.force.z, _x.goal_force.wrench.torque.x, _x.goal_force.wrench.torque.y, _x.goal_force.wrench.torque.z, _x.attractor_force.header.seq, _x.attractor_force.header.stamp.secs, _x.attractor_force.header.stamp.nsecs,) = _get_struct_6d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attractor_force.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attractor_force.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.attractor_force.wrench.force.x, _x.attractor_force.wrench.force.y, _x.attractor_force.wrench.force.z, _x.attractor_force.wrench.torque.x, _x.attractor_force.wrench.torque.y, _x.attractor_force.wrench.torque.z, _x.obstacles_forces.header.seq, _x.obstacles_forces.header.stamp.secs, _x.obstacles_forces.header.stamp.nsecs,) = _get_struct_6d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.obstacles_forces.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.obstacles_forces.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacles_forces.wrench_array = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.WrenchStamped()
        _v6 = val1.header
        start = end
        end += 4
        (_v6.seq,) = _get_struct_I().unpack(str[start:end])
        _v7 = _v6.stamp
        _x = _v7
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v6.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v6.frame_id = str[start:end]
        _v8 = val1.wrench
        _v9 = _v8.force
        _x = _v9
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v10 = _v8.torque
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacles_forces.wrench_array.append(val1)
      _x = self
      start = end
      end += 12
      (_x.total_force.header.seq, _x.total_force.header.stamp.secs, _x.total_force.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.total_force.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.total_force.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.total_force.wrench.force.x, _x.total_force.wrench.force.y, _x.total_force.wrench.force.z, _x.total_force.wrench.torque.x, _x.total_force.wrench.torque.y, _x.total_force.wrench.torque.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.goal_force.header.seq, _x.goal_force.header.stamp.secs, _x.goal_force.header.stamp.nsecs))
      _x = self.goal_force.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d3I().pack(_x.goal_force.wrench.force.x, _x.goal_force.wrench.force.y, _x.goal_force.wrench.force.z, _x.goal_force.wrench.torque.x, _x.goal_force.wrench.torque.y, _x.goal_force.wrench.torque.z, _x.attractor_force.header.seq, _x.attractor_force.header.stamp.secs, _x.attractor_force.header.stamp.nsecs))
      _x = self.attractor_force.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d3I().pack(_x.attractor_force.wrench.force.x, _x.attractor_force.wrench.force.y, _x.attractor_force.wrench.force.z, _x.attractor_force.wrench.torque.x, _x.attractor_force.wrench.torque.y, _x.attractor_force.wrench.torque.z, _x.obstacles_forces.header.seq, _x.obstacles_forces.header.stamp.secs, _x.obstacles_forces.header.stamp.nsecs))
      _x = self.obstacles_forces.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.obstacles_forces.wrench_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacles_forces.wrench_array:
        _v11 = val1.header
        _x = _v11.seq
        buff.write(_get_struct_I().pack(_x))
        _v12 = _v11.stamp
        _x = _v12
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v11.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v13 = val1.wrench
        _v14 = _v13.force
        _x = _v14
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v15 = _v13.torque
        _x = _v15
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3I().pack(_x.total_force.header.seq, _x.total_force.header.stamp.secs, _x.total_force.header.stamp.nsecs))
      _x = self.total_force.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.total_force.wrench.force.x, _x.total_force.wrench.force.y, _x.total_force.wrench.force.z, _x.total_force.wrench.torque.x, _x.total_force.wrench.torque.y, _x.total_force.wrench.torque.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_force is None:
        self.goal_force = geometry_msgs.msg.WrenchStamped()
      if self.attractor_force is None:
        self.attractor_force = geometry_msgs.msg.WrenchStamped()
      if self.obstacles_forces is None:
        self.obstacles_forces = iri_object_transportation_msgs.msg.wrenchStampedArray()
      if self.total_force is None:
        self.total_force = geometry_msgs.msg.WrenchStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.goal_force.header.seq, _x.goal_force.header.stamp.secs, _x.goal_force.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_force.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_force.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.goal_force.wrench.force.x, _x.goal_force.wrench.force.y, _x.goal_force.wrench.force.z, _x.goal_force.wrench.torque.x, _x.goal_force.wrench.torque.y, _x.goal_force.wrench.torque.z, _x.attractor_force.header.seq, _x.attractor_force.header.stamp.secs, _x.attractor_force.header.stamp.nsecs,) = _get_struct_6d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.attractor_force.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.attractor_force.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.attractor_force.wrench.force.x, _x.attractor_force.wrench.force.y, _x.attractor_force.wrench.force.z, _x.attractor_force.wrench.torque.x, _x.attractor_force.wrench.torque.y, _x.attractor_force.wrench.torque.z, _x.obstacles_forces.header.seq, _x.obstacles_forces.header.stamp.secs, _x.obstacles_forces.header.stamp.nsecs,) = _get_struct_6d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.obstacles_forces.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.obstacles_forces.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacles_forces.wrench_array = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.WrenchStamped()
        _v16 = val1.header
        start = end
        end += 4
        (_v16.seq,) = _get_struct_I().unpack(str[start:end])
        _v17 = _v16.stamp
        _x = _v17
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v16.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v16.frame_id = str[start:end]
        _v18 = val1.wrench
        _v19 = _v18.force
        _x = _v19
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v20 = _v18.torque
        _x = _v20
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.obstacles_forces.wrench_array.append(val1)
      _x = self
      start = end
      end += 12
      (_x.total_force.header.seq, _x.total_force.header.stamp.secs, _x.total_force.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.total_force.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.total_force.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.total_force.wrench.force.x, _x.total_force.wrench.force.y, _x.total_force.wrench.force.z, _x.total_force.wrench.torque.x, _x.total_force.wrench.torque.y, _x.total_force.wrench.torque.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_6d3I = None
def _get_struct_6d3I():
    global _struct_6d3I
    if _struct_6d3I is None:
        _struct_6d3I = struct.Struct("<6d3I")
    return _struct_6d3I
