// Generated by gencpp from file gesture_pkg/CameraInfo.msg
// DO NOT EDIT!


#ifndef GESTURE_PKG_MESSAGE_CAMERAINFO_H
#define GESTURE_PKG_MESSAGE_CAMERAINFO_H

#include <ros/service_traits.h>


#include <gesture_pkg/CameraInfoRequest.h>
#include <gesture_pkg/CameraInfoResponse.h>


namespace gesture_pkg
{

struct CameraInfo
{

typedef CameraInfoRequest Request;
typedef CameraInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraInfo
} // namespace gesture_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gesture_pkg::CameraInfo > {
  static const char* value()
  {
    return "1e0f6cc9c6dfad0bee4253b15158a925";
  }

  static const char* value(const ::gesture_pkg::CameraInfo&) { return value(); }
};

template<>
struct DataType< ::gesture_pkg::CameraInfo > {
  static const char* value()
  {
    return "gesture_pkg/CameraInfo";
  }

  static const char* value(const ::gesture_pkg::CameraInfo&) { return value(); }
};


// service_traits::MD5Sum< ::gesture_pkg::CameraInfoRequest> should match
// service_traits::MD5Sum< ::gesture_pkg::CameraInfo >
template<>
struct MD5Sum< ::gesture_pkg::CameraInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gesture_pkg::CameraInfo >::value();
  }
  static const char* value(const ::gesture_pkg::CameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gesture_pkg::CameraInfoRequest> should match
// service_traits::DataType< ::gesture_pkg::CameraInfo >
template<>
struct DataType< ::gesture_pkg::CameraInfoRequest>
{
  static const char* value()
  {
    return DataType< ::gesture_pkg::CameraInfo >::value();
  }
  static const char* value(const ::gesture_pkg::CameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gesture_pkg::CameraInfoResponse> should match
// service_traits::MD5Sum< ::gesture_pkg::CameraInfo >
template<>
struct MD5Sum< ::gesture_pkg::CameraInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gesture_pkg::CameraInfo >::value();
  }
  static const char* value(const ::gesture_pkg::CameraInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gesture_pkg::CameraInfoResponse> should match
// service_traits::DataType< ::gesture_pkg::CameraInfo >
template<>
struct DataType< ::gesture_pkg::CameraInfoResponse>
{
  static const char* value()
  {
    return DataType< ::gesture_pkg::CameraInfo >::value();
  }
  static const char* value(const ::gesture_pkg::CameraInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GESTURE_PKG_MESSAGE_CAMERAINFO_H
