// Generated by gencpp from file gesture_pkg/CameraInfoRequest.msg
// DO NOT EDIT!


#ifndef GESTURE_PKG_MESSAGE_CAMERAINFOREQUEST_H
#define GESTURE_PKG_MESSAGE_CAMERAINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gesture_pkg
{
template <class ContainerAllocator>
struct CameraInfoRequest_
{
  typedef CameraInfoRequest_<ContainerAllocator> Type;

  CameraInfoRequest_()
    {
    }
  CameraInfoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraInfoRequest_

typedef ::gesture_pkg::CameraInfoRequest_<std::allocator<void> > CameraInfoRequest;

typedef boost::shared_ptr< ::gesture_pkg::CameraInfoRequest > CameraInfoRequestPtr;
typedef boost::shared_ptr< ::gesture_pkg::CameraInfoRequest const> CameraInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gesture_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gesture_pkg::CameraInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gesture_pkg/CameraInfoRequest";
  }

  static const char* value(const ::gesture_pkg::CameraInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::gesture_pkg::CameraInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gesture_pkg::CameraInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gesture_pkg::CameraInfoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GESTURE_PKG_MESSAGE_CAMERAINFOREQUEST_H
