command_eng = {
    0: "Station, more light",
    1: "Station, less light",
    2: "Station, up",
    3: "Station, down",
    4: "Station, more tilt",
    5: "Station, less tilt",
    6: "Robot, gun screwdriver",
    7: "Robot, elbow screwdriver",
    8: "Robot, hammer",
    9: "Robot, screwdriver",
    10: "Robot, lever",
    11: "Robot, windows control panel",
    12: "Robot, rearview mirror",
    13: "Robot, release",
    14: "Robot, come here",
    15: "Robot, go",
    16: "Robot, start (Restart)",
    17: "Robot, stop (Wait)",
    18: "Robot, right",
    19: "Robot, left",
    20: "Robot, up",
    21: "Robot, down",
    22: "Robot, forward",
    23: "Robot, backward"
}

command_ita = {
    0: "Stazione, più luce",
    1: "Stazione, meno luce",
    2: "Stazione, sù",
    3: "Stazione, giù",
    4: "Stazione, più inclinato",
    5: "Stazione, meno inclinato",
    6: "Robot, avvitatore elettrico",
    7: "Robot, avvitatore a gomito",
    8: "Robot, martello",
    9: "Robot, cacciavite",
    10: "Robot, leva",
    11: "Robot, mostrina comandi",
    12: "Robot, specchietto retrovisore",
    13: "Robot, rilascia",
    14: "Robot, vieni",
    15: "Robot, libero",
    16: "Robot, start",
    17: "Robot, stop",
    18: "Robot, destra",
    19: "Robot, sinistra",
    20: "Robot, su",
    21: "Robot, giù",
    22: "Robot, avanti",
    23: "Robot, indietro"
}